### Recuperar todas las películas
GET http://localhost:3000/products

### Recuperar una película por id
GET http://localhost:3000/sellers/65b2ff3b044ee3952ef68cfd

### Recuperar todas las películas por un género
GET http://localhost:3000/sellers?first_name=Victor%20Hugo

### Crear una película con POST
POST http://localhost:3000/billings?isNewBill=true
Content-Type: application/json

{
}
###
PATCH http://localhost:3000/billings/65c4122ca6f997f2503b27d7/addProduct
Content-Type: application/json

{
  "product":{
    "description": "KIT PRO 01 Hub 2 Plus, 01 MotionProtect, 01 MotionCam, 01 DoorProtect, 01 SpaceControl, 01 HomeSiren",
    "model":"Kit 02",
    "price_igv":820,
    "price_non_igv":694.92,
    "price_pen_igv":3173.4,
    "price_pen_non_igv":2689.3404,
    "reserved_quantity":12,
    "unit_price":150,
    "_id":"65a95bf2f2cbf2fe9f094084",
    "item":"5"
  },
  "with_igv":false,
  "money_type": "PEN",
  "_id":"65c4122ca6f997f2503b27d7"
}

###
PATCH http://localhost:3000/billings/65c4122ca6f997f2503b27d7/updateMoneyType
Content-Type: application/json

{
  "products":[
    {
      "description": "KIT PRO PLUS 01 Hub 2 Plus, 02 MotionCam, 02 DoorProtect, 01 SpaceControl, 01 HomeSiren",
      "model":"Kit 03",
      "price_igv":950,
      "price_non_igv":805.93,
      "price_pen_igv":3804,
      "price_pen_non_igv":3223.73,
      "unit_price":150,
      "_id":"65ba7d57d57146aaf06d57d4",
      "item":"1"
    }
  ],
  "with_igv":false,
  "money_type": "USD",
  "_id":"65c4122ca6f997f2503b27d7"
}

### Borrar una película
PATCH http://localhost:3000/money_catalog/65bd29e614a478e153acb027
Content-Type: application/json

{
  "exchange_value": 3.87
}

### Actualizar una película
PATCH http://localhost:3000/products/65ba7d57d57146aaf06d57d4
Content-Type: application/json

{
  "quantity": 25
}