### Recuperar todas las películas
GET http://localhost:3000/products

### Recuperar una película por id
GET http://localhost:3000/sellers/65b2ff3b044ee3952ef68cfd

### Recuperar todas las películas por un género
GET http://localhost:3000/sellers?first_name=Victor%20Hugo

### Crear una película con POST
POST http://localhost:3000/billings?isNewBill=true
Content-Type: application/json

{
}
###
PATCH http://localhost:3000/billings/65c4122ca6f997f2503b27d7/addProduct
Content-Type: application/json

{
  "product":  {
    "_id": "65bba8591d30de03dd91a5b6",
    "model": "MotionProtect",
    "description": "SENSOR DE MOVIMIENTO SIN CAMARA Detección IR e inalámbrico de movimiento",
    "price_non_igv": 58.47,
    "price_igv": 69,
    "price_pen_non_igv": 226.2789,
    "price_pen_igv": 267.03,
    "reserved_quantity":10,
    "unit_price":226.2789,
    "item":2
  },
  "_id":"65c4122ca6f997f2503b27d7"
}

###
PATCH http://localhost:3000/billings/65c4122ca6f997f2503b27d7/modifyProductQuantity
Content-Type: application/json

{
  "product":  {
    "_id": "65bba8591d30de03dd91a5b6",
    "reserved_quantity":10,
    "unit_price":226.2789,
    "item":2
  },
  "_id":"65c4122ca6f997f2503b27d7"
}

###
PATCH http://localhost:3000/billings/65c4122ca6f997f2503b27d7/deleteProduct
Content-Type: application/json

{
  "product":  {
    "_id": "65bba8591d30de03dd91a5b6",
    "item":3
  },
  "with_igv":false,
  "money_type": "PEN",
  "_id":"65c4122ca6f997f2503b27d7"
}

###
PATCH http://localhost:3000/billings/65c4122ca6f997f2503b27d7/updateWithIgv
Content-Type: application/json

{
  "products":[
    {
      "description": "KIT PRO PLUS 01 Hub 2 Plus, 02 MotionCam, 02 DoorProtect, 01 SpaceControl, 01 HomeSiren",
      "model":"Kit 03",
      "price_igv":950,
      "price_non_igv":805.93,
      "price_pen_igv":3804,
      "price_pen_non_igv":3223.73,
      "unit_price":150,
      "_id":"65ba7d57d57146aaf06d57d4",
      "item":1
    }
  ],
  "with_igv":false,
  "money_type": "USD",
  "_id":"65c4122ca6f997f2503b27d7"
}

### Actualizar una cotización
PATCH http://localhost:3000/billings/65c4122ca6f997f2503b27d7
Content-Type: application/json

{
  "company_name": "A REPRESENTACIONES ELRL.",
  "client_id": "65b2d9f7044ee3952ee13dd1",
  "seller_id": "65b2ff3b044ee3952ef68cfd",
  "seller_name": "Leyva Perochena",
  "expiration_time": 15
}

### Actualizar una película
PATCH http://localhost:3000/products/65ba7d57d57146aaf06d57d4
Content-Type: application/json

{
  "quantity": 25
}